//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupportBot.JsonTemplates", typeof(JsonTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;busObId&quot;: &quot;&quot;,
        ///  &quot;busObPublicId&quot;: &quot;&quot;,
        ///  &quot;busObRecId&quot;: &quot;&quot;,
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;Comments Entry&quot;,
        ///      &quot;fieldId&quot;: &quot;93db0f17616e9520ac3b0f4b6a9b721cbf221b7514&quot;,
        ///      &quot;name&quot;: &quot;CommentsEntry&quot;,
        ///      &quot;value&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;Updated By SupportBot&quot;,
        ///      &quot;fieldId&quot;: &quot;94238830680a208506e8d64e9daa2486d7fec098b8&quot;,
        ///      &quot;name&quot;: &quot;UpdatedBySupportBot&quot;,
        ///      &quot;value&quot;: true
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string addCommentToTicket {
            get {
                return ResourceManager.GetString("addCommentToTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;busObId&quot;: &quot;942394630967f982c038d0485aaf831df62ce064d7&quot;,
        ///  &quot;busObPublicId&quot;: &quot;&quot;,
        ///  &quot;busObRecId&quot;: &quot;&quot;,
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;Conversation&quot;,
        ///      &quot;fieldId&quot;: &quot;94239f06226226519b3daf4c7581d95e0d99e901f5&quot;,
        ///      &quot;name&quot;: &quot;Conversation&quot;,
        ///      &quot;value&quot;: &quot;&lt;conversation&gt;&quot;
        ///    },
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;CustomerDisplayName&quot;,
        ///      &quot;fieldId&quot;: &quot;9423946c414f8bc426853640b8876821d4b7770f5d&quot;,
        ///      &quot;name&quot;: &quot;CustomerDisplayName&quot;,
        ///      &quot;value&quot;: &quot;&lt;customerDi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string createIncident {
            get {
                return ResourceManager.GetString("createIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;busObId&quot;: &quot;942394630967f982c038d0485aaf831df62ce064d7&quot;,
        ///  &quot;filters&quot;: [
        ///    {
        ///      &quot;fieldId&quot;: &quot;9423946afabc1b73c6cc5c4d39b0dee7a7bffce12e&quot;,
        ///      &quot;operator&quot;: &quot;startswith&quot;,
        ///      &quot;value&quot;: &quot;BotMessage-&quot;
        ///    },
        ///    {
        ///      &quot;fieldId&quot;: &quot;9423946f4bf7ea10ca6b074c10a18b730d8c2cf72b&quot;,
        ///      &quot;operator&quot;: &quot;eq&quot;,
        ///      &quot;value&quot;: &quot;False&quot;
        ///    }
        ///  ],
        ///
        ///  &quot;includeLinks&quot;: false,
        ///  &quot;includeAllFields&quot;: true,
        ///  &quot;includeSchema&quot;: false,
        ///  &quot;pageNumber&quot;: 0,
        ///  &quot;pageSize&quot;: 0,
        ///  &quot;scope&quot;: &quot;Global&quot;
        ///}.
        /// </summary>
        internal static string getsearchresults {
            get {
                return ResourceManager.GetString("getsearchresults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;busObId&quot;: &quot;942394630967f982c038d0485aaf831df62ce064d7&quot;,
        ///  &quot;busObPublicId&quot;: &quot;&quot;,
        ///  &quot;busObRecId&quot;: &quot;&quot;,
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;PublicID&quot;,
        ///      &quot;fieldId&quot;: &quot;9423946bee5e47976f072046ae811019e475801732&quot;,
        ///      &quot;name&quot;: &quot;PublicID&quot;,
        ///      &quot;value&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;CustomerDisplayName&quot;,
        ///      &quot;fieldId&quot;: &quot;9423946c414f8bc426853640b8876821d4b7770f5d&quot;,
        ///      &quot;name&quot;: &quot;CustomerDisplayName&quot;,
        ///      &quot;value&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;dirty&quot;: tru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string likeKbase {
            get {
                return ResourceManager.GetString("likeKbase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;busObId&quot;: &quot;942394630967f982c038d0485aaf831df62ce064d7&quot;,
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;Conversation&quot;,
        ///      &quot;fieldId&quot;: &quot;94239f06226226519b3daf4c7581d95e0d99e901f5&quot;,
        ///      &quot;name&quot;: &quot;Conversation&quot;,
        ///      &quot;value&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;CustomerDisplayName&quot;,
        ///      &quot;fieldId&quot;: &quot;9423946c414f8bc426853640b8876821d4b7770f5d&quot;,
        ///      &quot;name&quot;: &quot;CustomerDisplayName&quot;,
        ///      &quot;value&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;Operation&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logCallDeflection {
            get {
                return ResourceManager.GetString("logCallDeflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;filters&quot;: [
        ///    {
        ///      &quot;fieldId&quot;: &quot;93734aaff77b19d1fcfd1d4b4aba1b0af895f25788&quot;,
        ///      &quot;operator&quot;: &quot;eq&quot;,
        ///      &quot;value&quot;: &quot;Tracy E Aubin&quot;
        ///    },
        ///    {
        ///      &quot;fieldId&quot;: &quot;6ae282c55e8e4266ae66ffc070c17fa3&quot;,
        ///      &quot;operator&quot;: &quot;eq&quot;,
        ///      &quot;value&quot;: &quot;12345&quot;
        ///    } ],
        ///  &quot;busObId&quot;: &quot;6dd53665c0c24cab86870a21cf6434ae&quot;,
        ///  &quot;includeLinks&quot;: false,
        ///  &quot;fields&quot;: [
        ///    &quot;6ae282c55e8e4266ae66ffc070c17fa3&quot;,
        ///    &quot;5eb3234ae1344c64a19819eda437f18d&quot;,
        ///    &quot;93e8ea93ff67fd95118255419690a50ef2d56f910c&quot;,
        ///    &quot;9365a6098398ff2551e1c14dd3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string retrieveSpecificIncident {
            get {
                return ResourceManager.GetString("retrieveSpecificIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;busObId&quot;: &quot;942394630967f982c038d0485aaf831df62ce064d7&quot;,
        ///  &quot;busObPublicId&quot;: &quot;&quot;,
        ///  &quot;busObRecId&quot;: &quot;&quot;,
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;Processed&quot;,
        ///      &quot;fieldId&quot;: &quot;9423946f4bf7ea10ca6b074c10a18b730d8c2cf72b&quot;,
        ///      &quot;name&quot;: &quot;Processed&quot;,
        ///      &quot;value&quot;: &quot;true&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string savebusinessobject {
            get {
                return ResourceManager.GetString("savebusinessobject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;busObId&quot;: &quot;942394630967f982c038d0485aaf831df62ce064d7&quot;,
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;PublicID&quot;,
        ///      &quot;fieldId&quot;: &quot;9423946bee5e47976f072046ae811019e475801732&quot;,
        ///      &quot;name&quot;: &quot;PublicID&quot;,
        ///      &quot;value&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;CustomerDisplayName&quot;,
        ///      &quot;fieldId&quot;: &quot;9423946c414f8bc426853640b8876821d4b7770f5d&quot;,
        ///      &quot;name&quot;: &quot;CustomerDisplayName&quot;,
        ///      &quot;value&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;Operation&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string subscribeToIssue {
            get {
                return ResourceManager.GetString("subscribeToIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;filters&quot;: [
        ///    {
        ///      &quot;fieldId&quot;: &quot;93734aaff77b19d1fcfd1d4b4aba1b0af895f25788&quot;,
        ///      &quot;operator&quot;: &quot;eq&quot;,
        ///      &quot;value&quot;: &quot;Tracy E Aubin&quot;
        ///    },
        ///    {
        ///      &quot;fieldId&quot;: &quot;5eb3234ae1344c64a19819eda437f18d&quot;,
        ///      &quot;operator&quot;: &quot;eq&quot;,
        ///      &quot;value&quot;: &quot;New&quot;
        ///    },
        ///    {
        ///      &quot;fieldId&quot;: &quot;5eb3234ae1344c64a19819eda437f18d&quot;,
        ///      &quot;operator&quot;: &quot;eq&quot;,
        ///      &quot;value&quot;: &quot;In Cart&quot;
        ///    },
        ///    {
        ///      &quot;fieldId&quot;: &quot;5eb3234ae1344c64a19819eda437f18d&quot;,
        ///      &quot;operator&quot;: &quot;eq&quot;,
        ///      &quot;value&quot;: &quot;Assigned&quot;
        ///    },
        ///    {
        ///      &quot;fieldId&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string userIncidentList {
            get {
                return ResourceManager.GetString("userIncidentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;busObId&quot;: &quot;&quot;,
        ///  &quot;busObPublicId&quot;: &quot;&quot;,
        ///  &quot;busObRecId&quot;: &quot;&quot;,
        ///  &quot;fields&quot;: [
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;Comments Entry&quot;,
        ///      &quot;fieldId&quot;: &quot;93db0f17616e9520ac3b0f4b6a9b721cbf221b7514&quot;,
        ///      &quot;name&quot;: &quot;CommentsEntry&quot;,
        ///      &quot;value&quot;: &quot;withdrawn&quot;
        ///    },
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayName&quot;: &quot;Updated By SupportBot&quot;,
        ///      &quot;fieldId&quot;: &quot;94238830680a208506e8d64e9daa2486d7fec098b8&quot;,
        ///      &quot;name&quot;: &quot;UpdatedBySupportBot&quot;,
        ///      &quot;value&quot;: true
        ///    },
        ///    {
        ///      &quot;dirty&quot;: true,
        ///      &quot;displayN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string withdrawTicket {
            get {
                return ResourceManager.GetString("withdrawTicket", resourceCulture);
            }
        }
    }
}
